# Generated by Django 3.2.7 on 2021-09-28 05:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('courseNo', models.IntegerField(max_length=20)),
                ('instructor', models.CharField(max_length=75)),
                ('duration', models.FloatField(max_length=20)),
            ],
            managers=[
                ('djClasses', django.db.models.manager.Manager()),
            ],
        ),
    ]
