# Generated by Django 3.2.7 on 2021-09-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='courseNo',
            field=models.IntegerField(),
        ),
    ]
